name: emotion_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  get:
  get_storage:
  flutter_lints:
  freezed_annotation:
  dartz:
  json_serializable:
  rxdart:
  flutter_screenutil:

  firebase_auth:
  firebase_messaging:
  firebase_core: ^3.8.0
  cloud_firestore:
  flutter_svg: ^2.0.14
  flutter_spinkit: ^5.2.1
  table_calendar: ^3.1.2
  gender_picker: ^1.1.0
  cool_dropdown: ^2.1.1
  day_night_time_picker: ^1.3.1
  alarm: ^4.1.0
  permission_handler: ^11.3.1
  animated_emoji: ^3.1.0
  flutter_reaction_button: ^3.0.0+3
  avatar_plus: ^0.0.5
  local_auth: ^2.3.0

dev_dependencies:
  build_runner:
  freezed:

  # #to make native splash screen
  # # 1) change path image_path
  # # 2) run commened -> flutter pub run flutter_native_splash:create
  #   flutter_native_splash: ^2.1.1
  # flutter_native_splash:
  #   background_image: assets/image/splash_background.png # choose one color or background
  #   color: "#ffffff"
  #   image: assets/icons/icon.png

  # # to change icon
  # # 1) change path image_path
  # # 2) run commened -> flutter pub run flutter_launcher_icons:main
  #   flutter_launcher_icons: ^0.9.2
  # flutter_icons:
  #   android: true
  #   ios: true
  #   remove_alpha_ios: true
  #   image_path: "assets/icons/icon.png"

  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/image/
    - assets/animation/
    - assets/audio/
    - assets/svg/


  uses-material-design: true
