// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh6SvCc6LmXAVOMvD-ouzuoTyTBX65aZk',
    appId: '1:52163657696:android:3d7f772c443095451b3585',
    messagingSenderId: '52163657696',
    projectId: 'emotion-tracker-7728e',
    databaseURL: 'https://emotion-tracker-7728e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emotion-tracker-7728e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX__5Rgx1rvRSnDLSw0e9g3mBDxuAVTIs',
    appId: '1:52163657696:ios:1b60191f69d829b91b3585',
    messagingSenderId: '52163657696',
    projectId: 'emotion-tracker-7728e',
    databaseURL: 'https://emotion-tracker-7728e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emotion-tracker-7728e.firebasestorage.app',
    androidClientId: '52163657696-qv3vdqapahpmtjb3arlfkv5mce9l2i97.apps.googleusercontent.com',
    iosClientId: '52163657696-smsv37ff54i8lhurhp2fhg1l92c4gb0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.emotionTracker',
  );

}